# Generated by Django 4.1.5 on 2023-02-03 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='resume',
            field=models.CharField(blank=True, max_length=500, null=None),
        ),
    ]
