# Generated by Django 4.1.5 on 2023-02-03 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='resume',
            field=models.TextField(blank=True, max_length=500, null=None),
        ),
    ]
